// Content Exporter — bundle host content into an installable plugin zip.
//
// What it does
// ────────────
//   * Adds an "Export Pack" DM tab with creature/spell pickers.
//   * On Export, fetches the host's /api/creatures/export and
//     /api/spell-library/export endpoints (the host already ships
//     these — they emit JSON with embedded images, so the resulting
//     pack is fully self-contained).
//   * Wraps the JSON dumps inside a generated `client.js` that, when
//     installed elsewhere, auto-imports its content via the host's
//     existing /api/creatures/import + /api/spell-library/import
//     endpoints. The generated client tracks every inserted id in
//     plugin KV and removes them on `unregister` — so disabling the
//     exported pack returns the library to its previous state.
//   * Builds the final zip in-browser using a tiny inline STORE-method
//     ZIP encoder (no external deps — plugins ship as static files
//     and adding a CDN dependency would be a security/availability
//     foot-gun the host can't validate).
//
// How "exported = installable" stays true
// ───────────────────────────────────────
//   The host's plugin manager accepts uploads via Plugins → Upload
//   plugin .zip. The zip layout the manager expects is described in
//   PLUGINS.md §2 (manifest at root, files served as static assets).
//   Our zip matches that layout exactly:
//       <id>/plugin.json
//       <id>/client.js
//       <id>/data/creatures.json
//       <id>/data/spells.json
//   The host's installer extracts under backend/plugins/<id>/ — the
//   client.js then reads its own data files via fetch on the
//   plugin's static-asset URL (`/api/plugins/<id>/asset/...`).

const PLUGIN_ID = 'content-exporter';
const RUNTIME_TEMPLATE_PATH = null;   // baked inline below — see RUNTIME_TEMPLATE

// ── Runtime template — the client.js the EXPORTED plugin will run ──
// Stays as a plain string we substitute pluginId/version into. Keeping
// it inline (instead of a sibling file shipped in the exporter) means
// a single download produces a complete pack — no chained fetches.
const RUNTIME_TEMPLATE = `// Auto-generated by Content Exporter (TableTop Forge).
// On enable, this plugin imports its bundled creatures + spells into
// the host library, and pushes any bundled treasure items into the DM
// treasure chest. It tracks every inserted id; on disable it removes
// the library rows it created (treasure chest items aren't tracked
// because the chest is ephemeral DM state — closing the session
// already discards them).

const PLUGIN_ID = __PLUGIN_ID__;
const KEY_CREATURE_IDS = 'inserted_creature_ids';
const KEY_SPELL_IDS    = 'inserted_spell_ids';
const KEY_TERRAIN_IDS  = 'inserted_terrain_ids';
const KEY_TREASURE_LOADED = 'treasure_loaded_v1';
const KEY_CONTENT_LOADED  = 'content_loaded_v1';
const KEY_STATUS       = 'install_status';

const tabSubs = new Set();
function pingTab() { for (const fn of tabSubs) try { fn(); } catch {} }

let savedDataApi = null;
let creatureIds = [];
let spellIds    = [];
let terrainIds  = [];
let treasureCount = 0;
let installState = 'idle';
let installError = null;

async function readDataFile(rel) {
  // /api/plugins/<id>/asset/... is the host's static-asset path.
  const res = await fetch(\`/api/plugins/\${PLUGIN_ID}/asset/\${rel}\`);
  if (!res.ok) throw new Error(\`Could not read \${rel}: \${res.status}\`);
  return res.json();
}

async function importCreatures() {
  const dump = await readDataFile('data/creatures.json').catch(() => null);
  if (!dump || !Array.isArray(dump.creatures) || dump.creatures.length === 0) return 0;
  const fd = new FormData();
  const blob = new Blob([JSON.stringify(dump)], { type: 'application/json' });
  fd.append('file', blob, 'creatures.json');
  const res = await fetch('/api/creatures/import', { method: 'POST', body: fd });
  if (!res.ok) throw new Error(\`/api/creatures/import \${res.status}\`);
  const out = await res.json();
  const ids = (out.creatures || []).map((c) => c.id).filter((n) => Number.isFinite(n));
  creatureIds = [...creatureIds, ...ids];
  return ids.length;
}

async function importTreasure(dataApi) {
  // Treasure chest is purely DM-side state; only the DM client has the
  // host accessor populated. On player clients window.__tabletopForge
  // is undefined and this is a no-op. Only push once per install — the
  // KV flag avoids double-loading when the plugin is reloaded mid-
  // session for any reason (server hot-reload, manifest tweak, etc.).
  if (typeof window === 'undefined') return 0;
  const ns = window.__tabletopForge && window.__tabletopForge.treasure;
  if (!ns || typeof ns.addItems !== 'function') return 0;
  let alreadyLoaded = false;
  try { alreadyLoaded = !!(await dataApi.read(KEY_TREASURE_LOADED)); } catch {}
  if (alreadyLoaded) return 0;
  const dump = await readDataFile('data/treasure.json').catch(() => null);
  if (!dump || !Array.isArray(dump.items) || dump.items.length === 0) return 0;
  const added = ns.addItems(dump.items);
  treasureCount = added;
  try { await dataApi.write(KEY_TREASURE_LOADED, true); } catch {}
  return added;
}

async function importSpells() {
  const dump = await readDataFile('data/spells.json').catch(() => null);
  if (!dump || !Array.isArray(dump.spells) || dump.spells.length === 0) return 0;
  const fd = new FormData();
  const blob = new Blob([JSON.stringify(dump)], { type: 'application/json' });
  fd.append('file', blob, 'spells.json');
  const res = await fetch('/api/spell-library/import', { method: 'POST', body: fd });
  if (!res.ok) throw new Error(\`/api/spell-library/import \${res.status}\`);
  // The host's spell import returns { imported, skipped, total } only — no
  // ids. Resolve the inserted ids by name match against /api/spell-library.
  const names = new Set(dump.spells.map((s) => (s.name || '').toLowerCase()));
  const lib = await fetch('/api/spell-library').then((r) => r.json()).catch(() => []);
  const ids = (lib || [])
    .filter((s) => names.has((s.name || '').toLowerCase()))
    .map((s) => s.id)
    .filter(Boolean);
  // Only track ids we don't already know about so a re-enable doesn't
  // double-count manually-rolled spells with a colliding name.
  const have = new Set(spellIds);
  for (const id of ids) if (!have.has(id)) spellIds.push(id);
  return ids.length;
}

async function importTerrain() {
  const dump = await readDataFile('data/terrain.json').catch(() => null);
  if (!dump || !Array.isArray(dump.terrain) || dump.terrain.length === 0) return 0;
  const res = await fetch('/api/terrain/library/import', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(dump),
  });
  if (!res.ok) throw new Error(\`/api/terrain/library/import \${res.status}\`);
  const out = await res.json();
  const ids = (out.terrain || []).map((t) => t.id).filter((n) => Number.isFinite(n));
  terrainIds = [...terrainIds, ...ids];
  return ids.length;
}

async function deleteAllTracked() {
  const cTodo = [...creatureIds]; creatureIds = [];
  for (const id of cTodo) {
    try { const r = await fetch(\`/api/creatures/\${id}\`, { method: 'DELETE' }); if (!r.ok) throw new Error(); }
    catch { creatureIds.push(id); }
  }
  const sTodo = [...spellIds]; spellIds = [];
  for (const id of sTodo) {
    try { const r = await fetch(\`/api/spell-library/\${id}\`, { method: 'DELETE' }); if (!r.ok) throw new Error(); }
    catch { spellIds.push(id); }
  }
  const tTodo = [...terrainIds]; terrainIds = [];
  for (const id of tTodo) {
    try { const r = await fetch(\`/api/terrain/library/\${id}\`, { method: 'DELETE' }); if (!r.ok) throw new Error(); }
    catch { terrainIds.push(id); }
  }
}

export default {
  async register({ React, registries, context }) {
    const { data, role } = context;
    savedDataApi = data;

    try {
      const cs = await data.read(KEY_CREATURE_IDS);
      if (Array.isArray(cs)) creatureIds = cs.map(Number).filter(Number.isFinite);
      const ss = await data.read(KEY_SPELL_IDS);
      if (Array.isArray(ss)) spellIds = ss.filter((s) => typeof s === 'string');
      const ts = await data.read(KEY_TERRAIN_IDS);
      if (Array.isArray(ts)) terrainIds = ts.map(Number).filter(Number.isFinite);
    } catch { /* network blip */ }

    // Content packs must NOT re-import on every plugin load. The plugin
    // module loads fresh on every page reload while enabled, so without
    // this guard each refresh would POST the bundled creatures+spells
    // again, accumulating duplicates with new ids the previous run had
    // no way to track. The KV flag is set after first successful import
    // and survives plugin disable→enable cycles (KV is preserved by
    // host design); it's only cleared when the plugin's unregister
    // tears the rows back out, so a subsequent re-enable correctly
    // re-imports.
    let alreadyLoaded = false;
    try { alreadyLoaded = !!(await data.read(KEY_CONTENT_LOADED)); } catch {}

    (async () => {
      installState = 'installing'; installError = null; pingTab();
      try {
        if (!alreadyLoaded) {
          await importCreatures();
          await importSpells();
          try { await importTerrain(); } catch (terrainErr) { console.warn('terrain import failed', terrainErr); }
          try { await data.write(KEY_CONTENT_LOADED, true); } catch {}
        }
        // Treasure last — it's DM-only and best-effort. A failure here
        // shouldn't roll back the library imports.
        try { await importTreasure(data); } catch { /* DM-only, non-fatal */ }
        installState = 'installed';
      } catch (err) {
        installError = err.message || String(err);
        installState = 'failed';
      }
      try {
        if (!alreadyLoaded) {
          await data.write(KEY_CREATURE_IDS, creatureIds);
          await data.write(KEY_SPELL_IDS, spellIds);
          await data.write(KEY_TERRAIN_IDS, terrainIds);
        }
        await data.write(KEY_STATUS, { state: installState, error: installError });
      } catch {}
      pingTab();
    })();

    if (role !== 'dm') return;

    function PackTab() {
      const [, force] = React.useState(0);
      React.useEffect(() => {
        const fn = () => force((x) => (x + 1) | 0);
        tabSubs.add(fn);
        return () => tabSubs.delete(fn);
      }, []);
      return React.createElement('div',
        { className: 'p-4 space-y-3' },
        React.createElement('h3', { className: 'text-sm font-semibold text-dnd-gold mb-1' }, __PACK_NAME__),
        React.createElement('div', { className: 'space-y-2 bg-gray-800 border border-gray-700 rounded-lg p-3' },
          React.createElement('div', { className: 'text-xs text-gray-300' },
            'State: ', React.createElement('span', { className: 'font-mono text-dnd-gold' }, installState)),
          React.createElement('div', { className: 'text-xs text-gray-300' },
            \`Inserted creatures: \${creatureIds.length}\`),
          React.createElement('div', { className: 'text-xs text-gray-300' },
            \`Inserted spells: \${spellIds.length}\`),
          React.createElement('div', { className: 'text-xs text-gray-300' },
            \`Inserted terrain pieces: \${terrainIds.length}\`),
          treasureCount > 0 && React.createElement('div', { className: 'text-xs text-gray-300' },
            \`Treasure items pushed: \${treasureCount}\`),
          installError && React.createElement('div',
            { className: 'text-[11px] text-red-300 bg-red-950/40 border border-red-900/40 rounded px-2 py-1' },
            installError),
          React.createElement('div', { className: 'text-[11px] text-gray-500 leading-snug border-t border-gray-700 pt-2' },
            'Disable this plugin from the Plugin Manager (Session tab) to remove the content it added.'),
        ));
    }

    registries.dmTabs.set(PLUGIN_ID, {
      label: \`📦 \${__PACK_NAME__}\`,
      render: () => React.createElement(PackTab, null),
    });
  },

  async unregister() {
    try {
      await deleteAllTracked();
      if (savedDataApi) {
        await savedDataApi.write(KEY_CREATURE_IDS, creatureIds);
        await savedDataApi.write(KEY_SPELL_IDS, spellIds);
        await savedDataApi.write(KEY_TERRAIN_IDS, terrainIds);
        // Clear the once-flag so a re-enable knows to re-import. We only
        // do this if everything cleaned up — partial failures keep the
        // tracking arrays populated so a retry on next disable can
        // finish them off.
        if (creatureIds.length === 0 && spellIds.length === 0 && terrainIds.length === 0) {
          try { await savedDataApi.delete(KEY_CONTENT_LOADED); } catch {}
          try { await savedDataApi.delete(KEY_TREASURE_LOADED); } catch {}
          await savedDataApi.delete(KEY_STATUS);
        }
      }
    } catch (err) {
      console.warn(\`\${PLUGIN_ID}: cleanup failed\`, err);
    }
    installState = 'idle';
    installError = null;
  },
};
`;

// ── Inline STORE-method ZIP encoder ────────────────────────────────
// We don't need compression — text inputs are small and the zip is
// downloaded once. STORE means the file content is written verbatim
// after a small header. Spec: PKWARE APPNOTE.TXT, sections 4.3.7 and
// 4.3.16 (we don't use ZIP64; payloads are kilobytes).
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    t[i] = c;
  }
  return t;
})();
function crc32(buf) {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function dosTime(d = new Date()) {
  const time = ((d.getHours() & 0x1F) << 11) | ((d.getMinutes() & 0x3F) << 5) | ((Math.floor(d.getSeconds() / 2)) & 0x1F);
  const date = (((d.getFullYear() - 1980) & 0x7F) << 9) | (((d.getMonth() + 1) & 0x0F) << 5) | (d.getDate() & 0x1F);
  return { time, date };
}

function buildZip(files) {
  // files: Array<{ path: string, content: Uint8Array }>
  const enc = new TextEncoder();
  const localChunks = [];
  const centralChunks = [];
  let offset = 0;
  const { time, date } = dosTime();

  for (const f of files) {
    const nameBytes = enc.encode(f.path);
    const data = f.content;
    const crc = crc32(data);
    const localHeader = new Uint8Array(30 + nameBytes.length);
    const dv = new DataView(localHeader.buffer);
    dv.setUint32(0, 0x04034b50, true);
    dv.setUint16(4, 20, true);                  // version needed
    dv.setUint16(6, 0, true);                   // general purpose flag
    dv.setUint16(8, 0, true);                   // method = STORE
    dv.setUint16(10, time, true);
    dv.setUint16(12, date, true);
    dv.setUint32(14, crc, true);
    dv.setUint32(18, data.length, true);        // compressed size
    dv.setUint32(22, data.length, true);        // uncompressed size
    dv.setUint16(26, nameBytes.length, true);
    dv.setUint16(28, 0, true);                  // extra len
    localHeader.set(nameBytes, 30);
    localChunks.push(localHeader, data);

    const centralHeader = new Uint8Array(46 + nameBytes.length);
    const cdv = new DataView(centralHeader.buffer);
    cdv.setUint32(0, 0x02014b50, true);
    cdv.setUint16(4, 20, true);                 // version made by
    cdv.setUint16(6, 20, true);                 // version needed
    cdv.setUint16(8, 0, true);                  // general purpose flag
    cdv.setUint16(10, 0, true);                 // method
    cdv.setUint16(12, time, true);
    cdv.setUint16(14, date, true);
    cdv.setUint32(16, crc, true);
    cdv.setUint32(20, data.length, true);
    cdv.setUint32(24, data.length, true);
    cdv.setUint16(28, nameBytes.length, true);
    cdv.setUint16(30, 0, true);                 // extra len
    cdv.setUint16(32, 0, true);                 // comment len
    cdv.setUint16(34, 0, true);                 // disk start
    cdv.setUint16(36, 0, true);                 // internal attrs
    cdv.setUint32(38, 0, true);                 // external attrs
    cdv.setUint32(42, offset, true);            // local header offset
    centralHeader.set(nameBytes, 46);
    centralChunks.push(centralHeader);

    offset += localHeader.length + data.length;
  }

  const localTotal = offset;
  const centralStart = localTotal;
  const centralSize = centralChunks.reduce((s, c) => s + c.length, 0);

  const eocd = new Uint8Array(22);
  const edv = new DataView(eocd.buffer);
  edv.setUint32(0, 0x06054b50, true);
  edv.setUint16(4, 0, true);                    // disk number
  edv.setUint16(6, 0, true);                    // disk where cd starts
  edv.setUint16(8, files.length, true);         // entries on this disk
  edv.setUint16(10, files.length, true);        // total entries
  edv.setUint32(12, centralSize, true);
  edv.setUint32(16, centralStart, true);
  edv.setUint16(20, 0, true);                   // comment length

  // Concatenate everything.
  const totalLen = localTotal + centralSize + eocd.length;
  const out = new Uint8Array(totalLen);
  let pos = 0;
  for (const chunk of localChunks)   { out.set(chunk, pos); pos += chunk.length; }
  for (const chunk of centralChunks) { out.set(chunk, pos); pos += chunk.length; }
  out.set(eocd, pos);
  return out;
}

// ── Module state for the exporter UI ───────────────────────────────
let creatures = [];
let spells = [];
let terrain = [];            // global terrain library
let treasure = [];           // mirror of host's treasure chest
let selCreatures = new Set();
let selSpells = new Set();
let selTerrain = new Set();  // selected terrain library ids
let selTreasure = new Set(); // selected treasure items by id
let lastError = null;
let busy = false;

let unsubTreasure = null;    // host-treasure subscription cleanup

const tabSubs = new Set();
function pingTab() { for (const fn of tabSubs) try { fn(); } catch {} }

async function refreshCreatures() {
  try {
    const r = await fetch('/api/creatures');
    if (!r.ok) return;
    creatures = await r.json();
  } catch (err) {
    console.warn('content-exporter: /api/creatures failed', err);
  }
}
async function refreshSpells() {
  try {
    const r = await fetch('/api/spell-library');
    if (!r.ok) return;
    spells = await r.json();
  } catch (err) {
    console.warn('content-exporter: /api/spell-library failed', err);
  }
}
async function refreshTerrain() {
  try {
    const r = await fetch('/api/terrain/library');
    if (!r.ok) return;
    terrain = await r.json();
  } catch (err) {
    console.warn('content-exporter: /api/terrain/library failed', err);
  }
}

// Pull initial treasure snapshot + subscribe to live updates so the
// exporter UI reflects DM additions to the chest without a refresh.
// Only available on the DM client — on the player view the host
// accessor is undefined and this is a no-op.
function attachTreasureBridge() {
  if (typeof window === 'undefined') return;
  const ns = window.__tabletopForge && window.__tabletopForge.treasure;
  if (!ns || typeof ns.getList !== 'function') return;
  treasure = ns.getList();
  if (typeof ns.subscribe === 'function') {
    unsubTreasure = ns.subscribe((next) => {
      treasure = Array.isArray(next) ? next.map(it => ({ ...it })) : [];
      // Drop selections for items the DM has removed from the chest.
      const live = new Set(treasure.map(it => it.id));
      for (const id of Array.from(selTreasure)) if (!live.has(id)) selTreasure.delete(id);
      pingTab();
    });
  }
  pingTab();
}

function sanitiseId(raw) {
  return String(raw || '').toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
}

function fillTemplate(tpl, vars) {
  let out = tpl;
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`__${k}__`).join(JSON.stringify(v));
  }
  return out;
}

async function buildAndDownload(meta) {
  busy = true; lastError = null; pingTab();
  try {
    const id = sanitiseId(meta.id);
    if (!/^[a-z0-9][a-z0-9_-]*$/.test(id)) throw new Error('Plugin id must be lowercase letters, numbers, "-" or "_".');

    const enc = new TextEncoder();
    const files = [];

    // 1) plugin.json
    const manifest = {
      id,
      name: meta.name || id,
      version: meta.version || '1.0.0',
      description: meta.description || `Generated content pack — ${meta.name || id}`,
      author: meta.author || 'Content Exporter',
      frontend_entry: 'client.js',
      extension_points: ['dmTabs'],
    };
    files.push({ path: `${id}/plugin.json`, content: enc.encode(JSON.stringify(manifest, null, 2)) });

    // 2) client.js — string-substituted template
    const client = fillTemplate(RUNTIME_TEMPLATE, {
      PLUGIN_ID: id,
      PACK_NAME: meta.name || id,
    });
    files.push({ path: `${id}/client.js`, content: enc.encode(client) });

    // 3) data/creatures.json
    if (selCreatures.size > 0) {
      const ids = Array.from(selCreatures).join(',');
      const r = await fetch(`/api/creatures/export?ids=${ids}`);
      if (!r.ok) throw new Error(`/api/creatures/export ${r.status}`);
      const text = await r.text();
      files.push({ path: `${id}/data/creatures.json`, content: enc.encode(text) });
    }

    // 4) data/spells.json
    if (selSpells.size > 0) {
      const ids = Array.from(selSpells).join(',');
      const r = await fetch(`/api/spell-library/export?ids=${ids}`);
      if (!r.ok) throw new Error(`/api/spell-library/export ${r.status}`);
      const text = await r.text();
      files.push({ path: `${id}/data/spells.json`, content: enc.encode(text) });
    }

    // 5) data/treasure.json — strips host-side row ids so the imported
    // pack doesn't collide with whatever ids the destination chest is
    // already using; the runtime re-mints fresh ones via addItems().
    if (selTreasure.size > 0) {
      const items = treasure
        .filter((it) => selTreasure.has(it.id))
        .map(({ id: _drop, ...rest }) => rest);
      if (items.length) {
        const json = JSON.stringify({ items }, null, 2);
        files.push({ path: `${id}/data/treasure.json`, content: enc.encode(json) });
      }
    }

    // 6) data/terrain.json — uses the host's export endpoint, which
    // embeds each piece's image as a base64 data URL so the dump is
    // fully self-contained on import (no shared filesystem assumed).
    if (selTerrain.size > 0) {
      const ids = Array.from(selTerrain).join(',');
      const r = await fetch(`/api/terrain/library/export?ids=${ids}`);
      if (!r.ok) throw new Error(`/api/terrain/library/export ${r.status}`);
      const text = await r.text();
      files.push({ path: `${id}/data/terrain.json`, content: enc.encode(text) });
    }

    if (files.length < 2) throw new Error('Pick at least one creature, spell, terrain piece, or treasure item.');

    const zipBytes = buildZip(files);
    const blob = new Blob([zipBytes], { type: 'application/zip' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${id}.zip`;
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  } catch (err) {
    lastError = err.message || String(err);
  } finally {
    busy = false; pingTab();
  }
}

export default {
  async register({ React, registries, context }) {
    const { role } = context;
    refreshCreatures().then(pingTab);
    refreshSpells().then(pingTab);
    refreshTerrain().then(pingTab);
    attachTreasureBridge();

    if (role !== 'dm') return;

    function ExportTab() {
      const [, force] = React.useState(0);
      React.useEffect(() => {
        const fn = () => force((x) => (x + 1) | 0);
        tabSubs.add(fn);
        return () => tabSubs.delete(fn);
      }, []);

      const [meta, setMeta] = React.useState({
        id: 'my-pack',
        name: 'My Pack',
        version: '1.0.0',
        description: '',
        author: '',
      });
      const [search, setSearch] = React.useState('');
      const [section, setSection] = React.useState('creatures');

      const matchesSearch = (s) => !search || (s || '').toLowerCase().includes(search.toLowerCase());
      const visibleCreatures = creatures.filter((c) => matchesSearch(c.name));
      const visibleSpells    = spells.filter((s) => matchesSearch(s.name));
      const visibleTerrain   = terrain.filter((t) => matchesSearch(t.name));
      const visibleTreasure  = treasure.filter((t) => matchesSearch(t.name));

      function toggleSet(set, key) {
        if (set.has(key)) set.delete(key); else set.add(key);
        pingTab();
      }
      function selectAllVisible(set, list, idField = 'id') {
        for (const it of list) set.add(it[idField]);
        pingTab();
      }
      function clearSet(set) { set.clear(); pingTab(); }

      const sectionBtn = (id, label, count) => React.createElement('button', {
        onClick: () => { setSection(id); setSearch(''); },
        className: `flex-1 text-xs py-1.5 rounded ${section === id
          ? 'bg-dnd-gold text-gray-900 font-semibold'
          : 'bg-gray-800 hover:bg-gray-700 text-gray-200'}`,
      }, `${label}${count ? ` (${count})` : ''}`);

      function ItemRow({ item, idField, set }) {
        const checked = set.has(item[idField]);
        return React.createElement('label',
          { className: 'flex items-center gap-2 px-2 py-1 hover:bg-gray-700/40 rounded cursor-pointer text-xs text-gray-200' },
          React.createElement('input', {
            type: 'checkbox',
            checked,
            onChange: () => toggleSet(set, item[idField]),
            className: 'accent-dnd-gold w-3.5 h-3.5',
          }),
          React.createElement('span', { className: 'truncate' }, item.name)
        );
      }

      return React.createElement('div',
        { className: 'p-4 space-y-3' },
        React.createElement('h3', { className: 'text-sm font-semibold text-dnd-gold mb-1' }, 'Export Content Pack'),
        React.createElement('p', { className: 'text-xs text-gray-400 leading-snug' },
          'Pick the creatures and spells you want to bundle, fill in the manifest fields, and download a .zip you can install via Plugins → Upload plugin .zip on any TableTop Forge instance.'),

        // Manifest fields.
        React.createElement('div', { className: 'space-y-2 bg-gray-800 border border-gray-700 rounded-lg p-3' },
          React.createElement('div', { className: 'text-[11px] uppercase tracking-wider text-gray-500' }, 'Manifest'),
          React.createElement('div', { className: 'grid grid-cols-2 gap-2' },
            React.createElement('input', {
              type: 'text', value: meta.id,
              onChange: (e) => setMeta({ ...meta, id: e.target.value }),
              placeholder: 'plugin-id',
              className: 'bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-sm text-white font-mono',
            }),
            React.createElement('input', {
              type: 'text', value: meta.version,
              onChange: (e) => setMeta({ ...meta, version: e.target.value }),
              placeholder: '1.0.0',
              className: 'bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-sm text-white font-mono',
            })),
          React.createElement('input', {
            type: 'text', value: meta.name,
            onChange: (e) => setMeta({ ...meta, name: e.target.value }),
            placeholder: 'Display name',
            className: 'w-full bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-sm text-white',
          }),
          React.createElement('input', {
            type: 'text', value: meta.description,
            onChange: (e) => setMeta({ ...meta, description: e.target.value }),
            placeholder: 'One-line description',
            className: 'w-full bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-sm text-white',
          }),
          React.createElement('input', {
            type: 'text', value: meta.author,
            onChange: (e) => setMeta({ ...meta, author: e.target.value }),
            placeholder: 'Author (optional)',
            className: 'w-full bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-sm text-white',
          })
        ),

        // Section toggle + search.
        React.createElement('div', { className: 'flex gap-1.5 flex-wrap' },
          sectionBtn('creatures', `Creatures`, selCreatures.size),
          sectionBtn('spells',    `Spells`,    selSpells.size),
          sectionBtn('terrain',   `Terrain`,   selTerrain.size),
          sectionBtn('treasure',  `Treasure`,  selTreasure.size)),
        React.createElement('input', {
          type: 'search', value: search,
          onChange: (e) => setSearch(e.target.value),
          placeholder: 'Filter by name…',
          className: 'w-full bg-gray-900 border border-gray-700 rounded px-2 py-1.5 text-sm text-white',
        }),

        // List + select-all controls.
        section === 'creatures' && React.createElement('div',
          { className: 'space-y-1 bg-gray-800 border border-gray-700 rounded-lg p-2 max-h-72 overflow-y-auto' },
          React.createElement('div', { className: 'flex gap-1.5 px-1 pb-1' },
            React.createElement('button', {
              onClick: () => selectAllVisible(selCreatures, visibleCreatures),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, `Select visible (${visibleCreatures.length})`),
            React.createElement('button', {
              onClick: () => clearSet(selCreatures),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, 'Clear')),
          visibleCreatures.length === 0
            ? React.createElement('div', { className: 'text-xs text-gray-500 italic px-2 py-2' },
                creatures.length === 0 ? 'Loading…' : 'No matches.')
            : visibleCreatures.map((c) => React.createElement(ItemRow, {
                key: c.id, item: c, idField: 'id', set: selCreatures,
              }))
        ),
        section === 'spells' && React.createElement('div',
          { className: 'space-y-1 bg-gray-800 border border-gray-700 rounded-lg p-2 max-h-72 overflow-y-auto' },
          React.createElement('div', { className: 'flex gap-1.5 px-1 pb-1' },
            React.createElement('button', {
              onClick: () => selectAllVisible(selSpells, visibleSpells),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, `Select visible (${visibleSpells.length})`),
            React.createElement('button', {
              onClick: () => clearSet(selSpells),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, 'Clear')),
          visibleSpells.length === 0
            ? React.createElement('div', { className: 'text-xs text-gray-500 italic px-2 py-2' },
                spells.length === 0 ? 'Loading…' : 'No matches.')
            : visibleSpells.map((s) => React.createElement(ItemRow, {
                key: s.id, item: s, idField: 'id', set: selSpells,
              }))
        ),

        // Terrain — global library, fetched from /api/terrain/library
        // on register. Each piece's image is embedded as base64 by the
        // host's export endpoint (see buildAndDownload above), so the
        // pack is fully self-contained.
        section === 'terrain' && React.createElement('div',
          { className: 'space-y-1 bg-gray-800 border border-gray-700 rounded-lg p-2 max-h-72 overflow-y-auto' },
          React.createElement('div', { className: 'flex gap-1.5 px-1 pb-1' },
            React.createElement('button', {
              onClick: () => selectAllVisible(selTerrain, visibleTerrain),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, `Select visible (${visibleTerrain.length})`),
            React.createElement('button', {
              onClick: () => clearSet(selTerrain),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, 'Clear')),
          terrain.length === 0
            ? React.createElement('div', { className: 'text-xs text-gray-500 italic px-2 py-2' },
                "No terrain pieces in the library yet. Upload art via the Terrain panel and they'll show up here.")
            : visibleTerrain.length === 0
              ? React.createElement('div', { className: 'text-xs text-gray-500 italic px-2 py-2' }, 'No matches.')
              : visibleTerrain.map((p) => React.createElement('label',
                  { key: p.id, className: 'flex items-center gap-2 px-2 py-1 hover:bg-gray-700/40 rounded cursor-pointer text-xs text-gray-200' },
                  React.createElement('input', {
                    type: 'checkbox',
                    checked: selTerrain.has(p.id),
                    onChange: () => toggleSet(selTerrain, p.id),
                    className: 'accent-dnd-gold w-3.5 h-3.5',
                  }),
                  React.createElement('span', { className: 'truncate flex-1' }, p.name || '(unnamed)'),
                  Array.isArray(p.custom_walls) && p.custom_walls.length > 0 && React.createElement('span',
                    { className: 'text-[9px] uppercase tracking-wider bg-gray-900/60 border border-gray-700 text-gray-400 px-1 rounded shrink-0' },
                    `${p.custom_walls.length} wall${p.custom_walls.length === 1 ? '' : 's'}`)
                ))
        ),

        // Treasure pulled live from the host's chest. The chest is DM-
        // ephemeral (no DB) — the host exposes window.__tabletopForge.
        // treasure for cross-plugin access. Items the DM removes from
        // the chest mid-export drop out of the list automatically via
        // the subscription set up in attachTreasureBridge().
        section === 'treasure' && React.createElement('div',
          { className: 'space-y-1 bg-gray-800 border border-gray-700 rounded-lg p-2 max-h-72 overflow-y-auto' },
          React.createElement('div', { className: 'flex gap-1.5 px-1 pb-1' },
            React.createElement('button', {
              onClick: () => selectAllVisible(selTreasure, visibleTreasure),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, `Select visible (${visibleTreasure.length})`),
            React.createElement('button', {
              onClick: () => clearSet(selTreasure),
              className: 'text-[11px] bg-gray-700 hover:bg-gray-600 text-gray-200 px-2 py-0.5 rounded',
            }, 'Clear')),
          treasure.length === 0
            ? React.createElement('div', { className: 'text-xs text-gray-500 italic px-2 py-2' },
                'The treasure chest is empty. Add items via the Treasure tab in the DM panel, then come back here.')
            : visibleTreasure.length === 0
              ? React.createElement('div', { className: 'text-xs text-gray-500 italic px-2 py-2' }, 'No matches.')
              : visibleTreasure.map((it) => React.createElement('label',
                  { key: it.id, className: 'flex items-center gap-2 px-2 py-1 hover:bg-gray-700/40 rounded cursor-pointer text-xs text-gray-200' },
                  React.createElement('input', {
                    type: 'checkbox',
                    checked: selTreasure.has(it.id),
                    onChange: () => toggleSet(selTreasure, it.id),
                    className: 'accent-dnd-gold w-3.5 h-3.5',
                  }),
                  React.createElement('span', { className: 'truncate flex-1' }, it.name || '(unnamed)'),
                  it.qty > 1 && React.createElement('span', { className: 'text-[10px] text-gray-500 shrink-0' }, `x${it.qty}`),
                  it.item_type && it.item_type !== 'item' && React.createElement('span',
                    { className: 'text-[9px] uppercase tracking-wider bg-gray-900/60 border border-gray-700 text-gray-400 px-1 rounded shrink-0' },
                    it.item_type === 'magic_item' ? 'magic' : it.item_type)
                ))
        ),

        // Download.
        React.createElement('button', {
          onClick: () => buildAndDownload(meta),
          disabled: busy || (selCreatures.size + selSpells.size + selTerrain.size + selTreasure.size === 0),
          className: 'w-full bg-dnd-gold hover:bg-yellow-500 text-gray-900 py-2 rounded font-semibold text-sm disabled:opacity-50',
        }, busy
          ? 'Building…'
          : `Export ${selCreatures.size + selSpells.size + selTerrain.size + selTreasure.size} item(s) → ${sanitiseId(meta.id) || 'pack'}.zip`),
        lastError && React.createElement('div',
          { className: 'text-[11px] text-red-300 bg-red-950/40 border border-red-900/40 rounded px-2 py-1' },
          lastError)
      );
    }

    registries.dmTabs.set(PLUGIN_ID, {
      label: '📦 Export Pack',
      render: () => React.createElement(ExportTab, null),
    });
  },
  unregister() {
    if (typeof unsubTreasure === 'function') {
      try { unsubTreasure(); } catch {}
      unsubTreasure = null;
    }
    treasure = [];
    selTreasure.clear();
  },
};
